# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mboff < Formula
  desc "Optimise MBTiles by removing unnecessary data."
  homepage "https://github.com/jjcfrancisco/mboff"
  version "0.2.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jjcfrancisco/mboff/releases/download/v0.2.2/mboff_Darwin_arm64.tar.gz"
      sha256 "73bb9a7300568e64f7771e1cdc00821f6ec8ae735acfb410ad2d78d7fcb473b7"

      def install
        bin.install "mboff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jjcfrancisco/mboff/releases/download/v0.2.2/mboff_Darwin_x86_64.tar.gz"
      sha256 "051aee14e0ccc86f2c6472a53ec11060a556ff24d52d73739f9bb2aa240c8b67"

      def install
        bin.install "mboff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jjcfrancisco/mboff/releases/download/v0.2.2/mboff_Linux_arm64.tar.gz"
      sha256 "c58367a5b66a4b4d0663a0f39db4916458f70c2f1c9022dbd4a62268a66c026c"

      def install
        bin.install "mboff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jjcfrancisco/mboff/releases/download/v0.2.2/mboff_Linux_x86_64.tar.gz"
      sha256 "158ddb183d4ffebbd38fa2a19e14d69ff62f8c3dd3c2d91ab9fd90494e455323"

      def install
        bin.install "mboff"
      end
    end
  end
end
